-- phpMyAdmin SQL Dump
-- version 4.0.10.7
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: Sep 17, 2015 at 06:46 AM
-- Server version: 5.5.35-cll-lve
-- PHP Version: 5.4.31

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `roundnabout`
--

-- --------------------------------------------------------

--
-- Table structure for table `places`
--

DROP TABLE IF EXISTS `places`;
CREATE TABLE IF NOT EXISTS `places` (
  `id` int(4) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `latitude` float NOT NULL,
  `longitude` float NOT NULL,
  `category` varchar(255) NOT NULL,
  `email` varchar(255) DEFAULT NULL,
  `telephone` varchar(255) NOT NULL,
  `address` varchar(255) NOT NULL,
  `postcode` varchar(8) NOT NULL,
  `website` text,
  `entry_rates` varchar(255) NOT NULL,
  `opening_times` varchar(255) DEFAULT NULL,
  `rating` decimal(2,1) DEFAULT NULL,
  `more_info` text,
  `disabled_facilities` text,
  `facilities` text,
  `good_stuff` text,
  `bad_stuff` text,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=25 ;

--
-- Dumping data for table `places`
--

INSERT INTO `places` (`id`, `name`, `latitude`, `longitude`, `category`, `email`, `telephone`, `address`, `postcode`, `website`, `entry_rates`, `opening_times`, `rating`, `more_info`, `disabled_facilities`, `facilities`, `good_stuff`, `bad_stuff`) VALUES
(4, 'Hove Lagoon Skatepark', 50.8265, -0.195914, '["Skatepark,"Free"]', 'tony@pekuliar.com', '["07818543162"]', '["Hove Lagoon","Kingsway","Hove","East Sussex"]', 'BN3 4LX', NULL, '["FREE"]', '["24 Hours"]', '4.0', 'Hove Lagoon skatepark is a sweet little concrete skatepark, right on the coast with one of the coolest locations about a minutes walk from the beach. With a super smooth surface, it opens up both street and transition areas of the park with many flowing lines.\r\nThe skatepark comprises of a long 4 foot flat-bank with drop-in block at one end of the park, ideal for grinds, slides and stalls. This leads to the mid-section which is a big fun-box/driveway with flat and down, square kink rail in the middle, pyramid style hips to one side and steep hubbas to the other. This all leads to a 5 foot quarter-pipe to the left and flat-bank to the right, both connected to a 4½ foot mini the along the back wall of the skatepark.', '', 'Refreshments, toilets, cafe', 'Spine ramp in the centre of a street park. Great halfpipe all concrete park. Open 24 hours', 'nothing'),
(5, 'Beach Green Playpark', 50.8279, -0.279277, '["Playground"]', 'tony@pekuliar.com', '["07818543162"]', '["Beach Green","Shoreham"]', '', NULL, '["FREE"]', '["24 Hours"]', '4.0', 'A\r\nB\r\nC\r\nD', '', 'Toilets', 'Great Slide', 'Rubbish'),
(6, 'King Alfred Leisure Centre', 50.8251, -0.17895, '["Indoor","Leisure Centre"]', 'kingalfredenquiries@freedom-leisure.co.uk', '["01273 290290"]', '["Kingsway","Hove","East Sussex"]', 'BN3 2WW', NULL, '["Membership"]', '["8:30 a","m",null,"m",""]', '4.0', 'The wetside facilities include a 25m 6 lane swimming pool which ranges from a depth of 1.2 to 2.5m. There are two sports halls, based in the old pool halls.', '', '25m swimming pool with viewing area. Leisure pool with flume and fun pool features. Gym with cardiovascular and resistance equipment. 2 x sports halls (5-a-side football, badminton, volleyball, basketball, table tennis etc). Swim school - courses and individual lessons are available for all ages and abilities. Birthday parties. Junior gym sessions.', 'Recently refurbished, friendly staff, the changing room and shower area have all been renewed.', 'Run down, dirty in parts and baby pool not that warm. Lifeguards do not seem to police the lanes well which, sometimes, makes for unhappy customers!'),
(7, 'Huxleys Experience', 51.0533, -0.303792, '["Outdoor","Cost"]', 'huxleys@hotmail.co.uk', '["01403 273458"]', '["Falcon Lodge","Sedgwick Lane","Brighton road","Horsham","West Sussex"]', 'RH13 6QD', NULL, '[null,"95","",null,"95","",null,"25","",null,"50"]', '["Wednesday to Saturday and Bank Holidays 11am to 5pm","Sunday 11am to 4","30pm","Just Sundays in winter"]', '5.0', 'At the centre they have a wide range of birds from hawks to eagles, falcons to owls, and vultures to kites! They have around 70 birds in total all waiting to see you.\r\n\r\nThey even have a few character birds such as Coco the Crested Caracara, Reaper the Raven and Sydney the Laughing Kookaburra!\r\n\r\nThey have a special team of owls who take it in turns to meet and greet the public and 12noon and 2pm! They also have a fantastic flying team who love to show off in the 2:30pm display as well as at other various events and shows around the South of England.\r\n\r\nPlus a gorgeous Japanese Water Garden.', '', '', 'Amazing value for such a great afternoon. Very friendly, entertaining and knowledgeable staff, a good number of birds and a great flying display.', ''),
(8, 'Dunreyth Alpacas', 50.8788, -0.873511, '["Outdoor","Cost","Animals"]', 'info@dunreythalpacas.co.uk', '["Peta: 07766 252310 or Bruce: 07799 583637"]', '["Adsdean","Funtington","Chichester","West Sussex"]', 'PO18 9DN', NULL, '[null,""]', '["Open to visitors: Tuesday to Sunday from 9am to 4pm","Closed on Mondays"]', '3.0', 'Dunreyth Alpacas is a small business owned by a husband and wife team near Chichester on the side of the South Downs. Alpaca Walking. Walks have to be booked in advance. Minimum age is 6 years old. At least two Alpacas need to be booked per walk. The walk takes approx. 50 min.', '', 'Picnic tables. Toilets.', 'Nice countryside walk.', 'Quite expensive'),
(9, 'Woods Mill Nature Reserve', 50.9113, -0.266976, '["Outdoor","Free","Nature"]', 'enquiry@wildlifetrusts.org', '["01636 677711"]', '["Horn Lane","Small Dole","Henfield","Sussex","",""]', 'BN5 9SD', NULL, '["Free"]', '["Open throughout the year (except for two weeks at Christmas)"]', '4.0', 'Best time to visit is April - July.', '', 'Toilets, disabled toilet. Size is 13 hectares. All-weather path and boardwalk across lake and reedbed suitable for wheelchairs.Car park. No dogs allowed.', 'Free, beautiful walks.', 'Limited car parking'),
(10, 'Fishers Farm Park', 51.0306, -0.492098, '["Outdoor","Animals","Farm"]', 'info@fishersfarmpark.co.uk', '["01403 700063"]', '["Fishers Farm Park","Newpound Lane","Wisborough Green","West Sussex"]', 'RH14 0EG', NULL, '["2015 Prices:","","Mid Season Sample prices:","",null,"75","",null,"75","","Groups: see website for group discounts and fantastic options for schools and nurseries","Membership holders get 10% off everything! (including admission for friends and relative', '["Open All Year (closed Xmas day and boxing day only) Open:10m Close: 5pm"]', '4.0', 'Restaurant: Waitress service, home-cooked food and fantastic children’s options on the menu. Barista Coffee Bar: Freshly ground coffee conveniently located next to 5 different soft-play zones! Cafe Moo Moo: Moooove on down to this “udderly” brilliant cafe serving hot food fast for the busy visitor. Alpine Lodge. “Sugar and Spice and all things nice” with doughnuts, ice creams and treats for everyone. Splash Attack (seasonal): Drinks and ice creams served all day!', '', 'Toilets, disabled toilets, baby care centre, toy shop, mums microwaves, private nursing areas.', 'Mobility Scooters available for use and “Free of charge”', ''),
(11, 'Washbrooks Family Farm', 50.9314, -0.18266, '["Farm","Animals","Playground"]', NULL, '["01273 832201"]', '["Brighton Road","Hurstpierpoint","Hassocks","West Sussex"]', 'BN6 9EF', NULL, '[null,"",null,"50","",null,"50","",null,"50","","Family ticket (2 adults",null]', '["Open everyday from 9","30am until 5pm","Closed from Christmas Day until News Years Day",""]', '5.0', 'Indoor play area, tractor rides, outdoor adventure playground, giant bouncy pillow, living maize maze, sandpit. Lots of animals', '', 'Toilets, tea room, picnic facilities', 'Giant jumping pillow', ''),
(12, 'Woods Mill Nature Reserve', 50.9113, -0.266976, '["Outdoor","Free","Nature"]', 'enquiry@wildlifetrusts.org', '["01636 677711"]', '["Horn Lane","Small Dole","Henfield","Sussex","",""]', 'BN5 9SD', NULL, '["Free"]', '["Open throughout the year (except for two weeks at Christmas)"]', '4.0', 'Best time to visit is April - July.', '', 'Toilets, disabled toilet. Size is 13 hectares. All-weather path and boardwalk across lake and reedbed suitable for wheelchairs.Car park. No dogs allowed.', 'Free, beautiful walks.', 'Limited car parking'),
(13, 'Brighton Fishing Museum', 50.82, -0.142012, '["Free","Museum","Indoor"]', 'jessicapetitfishingmuseum@gmail.com', '["01273 723064"]', '["201 Kings Road","Brighton"]', 'BN1 1NB', NULL, '["Free"]', '["Open 7 days a week"]', '3.0', 'The Brighton Fishing Museum is located a short distance to the west of Brighton Pier in Brighton, Sussex, England. It opened in 1992 in the area known as the Fishing District in one of the arches on the Kings Road.', '', 'Full disabled access', 'Free', 'Very small'),
(14, 'Adur Recreation Ground', 50.8311, -0.2843, '["Free","Outdoor","Park"]', NULL, '[""]', '["Brighton Road","Shoreham-by-Sea","West Sussex",""]', 'BN43 5LT', NULL, '["Free"]', '[""]', '3.0', 'Large open space next to Adur River and Shoreham Airport. Multi-use site for events, car-boot sales, BMX track, model car club, two free carparks, outdoor centre and play area. Used by local residents, children and parents. An area of natural beauty with Dogs Trust as neighbours and lovely views in all directions.', '', '', '', ''),
(15, 'KnockHatch Adventure Park', 50.8637, 0.232136, '["Adventure Park","Paid","Water Fun","Rides","Outdoor"]', 'info@knockhatch.com', '["01323 442051"]', '["Knockhatch Adventure Park","Hailsham Bypass","Hailsham"]', 'BN27 3PR', NULL, '["Knockhatch Day Pass","","Peak\\tOff Peak","",null,"99",null,"99","",null,null,"99","",null,"99",null,"99","","Children under 2 years always free!","",null,"99",null,"99","","Extra child on family ticket",null,"99",null,"99","",null,"50","",null,"95","",n', '["10am to 5","30pm almost every day barring December 24 to 26 and January 1","Some elements are unavailable off season","check ahead to be sure if the kids are looking forward to something particular",""]', '4.9', 'Knockhatch Adventure Park has a frankly epic amount of activities to choose from, whether you like creatures, rides, challenges, games, family activities or simple kids'' fun there''s something for you here: great for if you''re packing a range of picky and choosy types!\r\nIt''s a neo-classic Adventure Park with Adventure Playgrounds, Birds of Prey displays, Rowing Boats, Animals to visit, Reptiles to recoil from, Giant Sky Leap Slide (and we mean giant!), Indoor Soft Play for attacks of British weather, Alpine Toboggan rides, Trampolines, Crazy Golf course, plus lots more.\r\nAt extra cost and weather permitting, Go-Karts, Laser Tag, Rodeo Bull, Rock Climbing, Bungee Trampoline, Ride on Mini Diggers, Ice Skating and April through September an Ice Magic Show! See: loads! We told you!\r\nKnockhatch Adventure Park also has a Kids'' Driving School in electric cars which provides loads of fun and excitement for children. Why not give them a try and practice some road skills. Height limit 0.9m to 1.3m.\r\nNew features include the Runaway Train Simulator ride and also Animal or Bird of Prey Encounter Experiences: a brilliant idea if you are stuck for a way to celebrate a special occasion or simply want something really different to do!', 'Yes', 'Toilets, Baby changing, cafe.', 'The Wave Runner ride is exceptional and is INCLUDED in the entrance price!', ''),
(16, 'Earnley Butterfly Farm', 50.7704, -0.837072, '["Indoor","Paid","Animals"]', 'earnleybutterflies@hotmail.co.uk', '["01243 512637"]', '["133","Almodington Lane","Earnley","Chichester","West Sussex"]', 'PO20 7JR', NULL, '[null,null,null,"50",null,null,"50 Family (2 adults",null,"00","Winter",null,""]', '["Summer Opening Times: Open 7 days a week from 14th March to 1st November","Open from 10am to 5pm daily","10am to 6pm on bank holiday weekends and school holidays","(Last entries 1 hour before closing time)","Winter Opening Times: Open from 11am - 3pm we', '2.6', 'Covered, themed gardens encompassing a tropical butterfly house and a walk-through aviary', NULL, 'Most areas accessible for wheel chairs. Some gravel paths. \r\nHMS Hazardous Shipwreck Display is not accessible to wheelchairs.', 'Being able to walk amongst butterflies and birds.', 'Overpriced, rundown & tatty'),
(17, 'Woods Mill Nature Reserve', 50.9111, -0.268346, '["Outdoor","Free","Nature"]', 'suedavies@sussexwt.org.uk', '["01273 492630"]', '["Woods Mill Nature Reserve","Shoreham Road","Henfield","West Sussex"]', 'BN5 9SD', NULL, '["Free"]', '["Open daily throughout the year dawn til dusk (except for two weeks during the Christmas period)"]', '3.6', 'Woods Mill Nature Reserve is an excellent place to take the kids for a walk through mixed habitats plus visit the Sussex Wildlife Trust environmental education centre.\r\nThere is something for the kids to see here, no matter what time of year you visit so it is a great place for to explore.\r\nThere are pond dipping sessions available during the Summer holidays, which are held by the Woods Mill warden and give kids a chance to get a close look at some of the wildlife living in the pond. The staff are very knowledgeable and happy to answer any questions kids may have about the creatures that they have netted.', NULL, 'Toilets', '', 'Dogs are not permitted. Some areas may not be suitable for some pushchairs or wheelchairs.'),
(18, 'Fishers Farm Park', 51.0308, -0.492147, '["Paid","Farm","Animals","Adventure", "Rides"]', 'info@fishersfarmpark.co.uk', '["01403 700063"]', '["Newpound Lane","Wisborough Green","West Sussex"]', 'RH14 0EG', NULL, '[null,"75",null,"75","Children under 2 FREE",null,null,"See website for group discounts"]', '["Open All Year (closed Xmas day and boxing day only) Open:10m Close: 5pm"]', '4.3', 'New Animal Barn with the adorable baby rabbits, tortoises and a variety of other small and cuddly creatures! Get up close to the giant Shire horses, Alpacas, Cows, Donkeys and more: learning everything there is to know about our fury friends!\r\nTwo soft-play centres, Tractor Rides, Ghost Tunnel, Climbing Wall, Toboggan Run, Adventure Golf, Pony Rides, Animal Racing, Theatre Shows and more than 40 different rides and attractions', NULL, 'Mobility Scooters available for use and “Free of charge”. Advise booking prior to visit on 01403 700063. Disabled toilets available in lots of places across the park and reservations can be made in Theatre for full access to the shows. Fishers Farm Park is ideal for parents, offering additional extras such as “Mum’s Microwaves” and “Private Nursing Areas” to make your day as easy as possible. If you’re visiting in the summer DONT FORGET YOUR SWIMWEAR! (For the “Beach Splash Attack” area)', 'Fishers Adventure Farm Park was officially announced this year as one of the ‘Best Farm Attractions in the UK’ and with all rides and activities included in your admission, Fishers is undoubtedly the ultimate day out for any family.', 'Some rides cost extra. Food is average.'),
(19, 'Washbrooks Family Farm', 50.9314, -0.182295, '["Paid","Farm","Animals","Adventure","Rides"]', 'enquire@washbrooks.co.uk', '["01273 832201"]', '["Brighton Road","Hurstpierpoint","Hassocks","West Sussex"]', 'BN6 9EF', NULL, '[null,"50",null,"50",null,null,"50","","Family ticket (2 adults",null]', '["Everyday from 9","30am-5pm","Closed from Christmas Day until News Years Day",""]', '4.4', 'A great environment for young children (up to the age of 8) to meet all their favourite farm animals under one roof and enjoy hours of play time in the large indoor and outdoor play areas. Great Indoor play area, nice cafe but also loads of picnic tables.', NULL, 'For wheelchair users, the majority of the farm is accessible with stone paths (with the exception of the far field walk), wide entrances to all buildings and fully equipped disabled toilet.', 'Good value for money. Lots of things to do. Clean and modern. Great day out.', 'Dogs (except guide dogs) aren’t permitted.'),
(20, 'Tulleys Farm', 51.1071, -0.111404, '["Paid","Farm","Animals","Adventure","Rides"]', 'info@tulleysfarm.com', '["01342 718472"]', '["Turners Hill Road","Crawley","West Sussex"]', 'RH10 4PD', NULL, '[null,null,"95","",null,null,"95","",null,null,"95","",null,null,"95"]', '["July to September: 10am - 6pm"]', '4.2', 'Mini mazes, giant games, illusions and entertainments, explore the larger mazes at night by torch light and enjoy rides, trampolines and frisbee golf course! Loads of seasonal bonus fun plus animal patch and tea room.', NULL, 'Toilets, farm shops, food', 'Farmers market with locally-grown produce, master butcher and an artisan bakery, plus a tearoom. Seasonal family events venue running a variety of attractions throughout the year including Shocktober Fest, Pumpkin Patch and the Spooktober Fest at Halloween, The Tulleys Family Christmas Experience, Christmas Shop and a swathe of Natural Christmas Trees, The Big Hatch Easter Experience and The Giant Maize Maze and Puzzle Park throughout the summer.', 'Queues can be long at times.'),
(21, 'Amberley Working Museum', 50.8975, -0.53996, '["Paid","Outdoor","Transport","Museum"]', 'office@amberleymuseum.co.uk', '["01798 831370"]', '["Houghton Bridge","","Arundel","","Amberley","","West Sussex"]', 'BN18 9LT', NULL, '[null,"",null,"",null,"",null,"","Children under 4 are free of charge","Well behaved dogs on leads also free",""]', '["4th March to 1st November (inclusive): Wednesday to Sunday 10am to 5pm","Last entry 4pm","Open on the following Mondays and Tuesdays: 6th and 7th April 4th","25th and 26th May 27th and 28th July Open every day in August 1st September 26th and 27th Octob', '4.6', 'Narrow gauge railway, vintage vehicle demos, old buildings and exhibitions in a former chalk quarry.', NULL, 'Toilets, Cafe', 'Value for money. Miniature steam train. Lots to see.', 'Prices of sandwiches abit pricey.'),
(22, 'Littlehampton Museum', 50.8094, -0.539334, '["Free","Museum","Indoor"]', 'museum@littlehampton-tc.gov.uk', '["01903 738100"]', '["Manor House","","Church St","","Littlehampton","West Sussex"]', 'BN17 5EW', NULL, '["Free"]', '["Mon-Fri 9","00am - 4","30pm","Sat 10","30am - 4","30pm","Closed 25th December - 1st January inclusive",""]', '3.2', 'Littlehampton Museum is located in the Grade II listed Manor House in the centre of the town, a short walk from the beach, and easily accessible by rail, road and bus. Home to five permanent galleries and two temporary exhibition spaces with interactive exhibits and fascinating collections, the museum has something to offer everybody.', NULL, 'Disabled access to all public areas, toilets', 'Free', ''),
(23, 'Tangmere Military Aviation Museum', 50.8468, -0.714749, '["Paid","Indoor","Museum","Transport"]', 'info@tangmere-museum.org.uk', '["01243 790 090"]', '["Tangmere","Chichester","West Sussex"]', 'PO20 2ES', NULL, '[null,"00*",null,"00","Children under 5: FREE",null,"00",null,"00",null]', '["Open every day between February 1st and November 30th","March to October: 10","00am to 5","00pm February and November: 10","00am to 4","30pm"]', '4.1', 'Flight simulators, memorial garden, air raid shelter, five different exhibition halls. Cafe sells soups, sandwiches and jacket potatoes, plus afternoon teas, with a covered terrace.', NULL, 'Shop, Cafe, Neville Duke Hall and Library. Toilets and an accessible toilet is available for wheelchair users. Guide dogs and hearing dogs are welcome throughout the Museum. Water bowls for guide dogs are available.', 'Friendly and helpful staff.', ''),
(24, 'Bognor Regis Museum', 50.7821, -0.678831, '["Free","Indoor","Museum"]', NULL, '["01243 865636"]', '[null,"Bognor Regis","West Sussex"]', 'PO21 1XA', NULL, '["Free admission but donations keep it running!"]', '["Opens April - October","Tues - Sun","plus Bank Holidays 10am to 4pm"]', '4.2', 'A really nice little museum. There is something of interest for all age groups and the staff are most welcoming and a mine of information about the town. I guarantee that you will see Bognor in a different light after visiting this gem.', NULL, '', 'Free, Dressing up for the children, staff very friendly and helpful.', '');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
